image:
  name: node:10.13

pages:
  stage: deploy
  environment: staging
  script:
  - curl https://raw.githubusercontent.com/helm/helm/master/scripts/get > get_helm.sh
  - chmod 700 get_helm.sh
  - ./get_helm.sh
  - helm init --client-only
  - npm install
  - npm run build
  artifacts:
    paths:
    - public
  only:
  - master

# deploy-to-prod:
#   type: deploy
#   environment: production
#   script:
#   - yarn install --pure-lockfile --cache-folder .yarn-cache
#   - npm run build
#   - aws s3 sync public/ s3://$AWS_BUCKET --acl public-read
#   when: manual
